name: "local"
net: 0x02
genesis_param:
  initial_incognito:
    - Version: 1
      Type: "s"
      LockTime: 1570159128
      SigPubKey: "5xVSzcZpA3uHmBO5ejENk13iayexILopySACdieLugA="
      Fee: 0
      Sig: "oMJPBLxKgTnfQhMgfvvH68ed0UTuTfl3ofOoWgk8dgvfhovgvued9HH4dXz60rY32H4Y4c85Zd8bSXSnvNhZAA=="
      Proof: "AAAAAAAAAbAAriDnFVLNxmkDe4eYE7l6MQ2TXeJrJ7EguinJIAJ2J4u6ACARCc1/qyLEePe1zSthzmRSqf2VNOlo036JwtDgbNg24yAb6hGuk1tRBVMO4ruHaNEasY09ZiBc4iuK/dpDSyNTCCABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDMoX8yNBbY68SO44umD1CMfz/r0T4YiXhDgDgT6+k4BgdY0V4XYoAAAAAAAAAAAAA="
      PubKeyLastByteSender: 0
  fee_per_tx_kb: 0
  consensus_algorithm: "bls"
  block_timestamp: "2019-11-29T00:00:00.000Z"
  tx_stake: "d0e731f55fa6c49f602807a6686a7ac769de4e04882bb5eaf8f4fe209f46535d"

committee_size:
  max_shard_committee_size: 4
  min_shard_committee_size: 4
  min_beacon_committee_size: 4
  max_beacon_committee_size: 7
  init_shard_committee_size: 4
  init_beacon_committee_size: 4
  shard_committee_size_key_list_v2: 4
  beacon_committee_size_key_list_v2: 4
  number_of_fixed_shard_block_validators: 4
  increase_max_shard_committee_size:
    - 1000000000000: 48
block_time:
  min_beacon_block_interval: 40s
  max_beacon_block_creation: 20s
  min_shard_block_interval: 40s
  max_shard_block_creation: 20s
staking_amount_shard: 1750000000000
active_shards: 2
basic_reward: 400000000
max_reward: 95000000000000000
epoch_param:
  number_of_block_in_epoch: 50
  number_of_block_in_epoch_v2: 1e9
  epoch_v2_break_point: 1e9
  random_time: 25
  random_time_v2: 1e9
eth_contract_address: "0xf90860014c7e13dE4A86B81c54dDE797820c72bE"
bsc_contract_address: "0x9ee4E8FE2D977c8869F2e29736b21e8fc6FF830E"
plg_contract_address: "0x141aa0C4c7d27f7B526a254202F979B60F056333"
ftm_contract_address: "0x526768A37feD86Fd8D5D72ca78913DFF64AC5E15"
prv_erc20_contract_address: "0xAbFf10a3F834517Fa106f4BAA4b4CB8D608517F7"
prv_bep20_contract_address: "0x0C61C7F99DeE0270a5934F1520d109dc44A51d6c"
dao_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci" # community fund
centralized_website_payment_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci"
swap_committee_param:
  offset: 1
  swap_offset: 1
  assign_offset: 2
consensus_param:
  consensus_v2_epoch: 1
  staking_flow_v2_height: 1
  enable_slashing_height: 1
  lemma2_height: 1e9
  byzantine_detector_height: 1e9
  assign_rule_v3_height: 1e9
  enable_slashing_height_v2: 1e9
  staking_flow_v3_height: 1e9
  force_not_use_burned_coins: 1
  block_producing_v3_height: 1e9
  timeslot: 10
  epoch_break_point_swap_new_key: # read from file key list v2
    - 1e9
beacon_height_break_point_burn_addr: 2
eth_remove_bridge_sig_epoch: 0
replace_staking_tx_height: 1
bc_height_break_point_new_zkp: 2
bc_height_break_point_privacy_v2: 1
coin_v2_lowest_height: 1
enable_feature_flags:
  - PortalRelaying: 1
  - PortalV3: 0
  - PortalV4: 1
portal_v3_height: 1e9
tx_pool_version: 0
geth_param:
  host: 
    - "https://kovan.infura.io/v3/1138a1e99b154b10bae5c382ad894361"
bsc_param:
  host: 
    - "https://data-seed-prebsc-1-s1.binance.org:8545"
    - "https://data-seed-prebsc-1-s2.binance.org:8545"
    - "https://data-seed-prebsc-2-s2.binance.org:8545"
    - "https://data-seed-prebsc-2-s3.binance.org:8545"
plg_param:
  host: 
    - "https://polygon-mumbai.g.alchemy.com/v2/V8SP0S8Q-sT35ca4VKH3Iwyvh8K8wTRn"
    - "https://rpc-mumbai.maticvigil.com"
    - "https://matic-mumbai.chainstacklabs.com"
ftm_param:
  host: 
    - "https://rpc.testnet.fantom.network"
pdex_param:
  pdex_v3_break_point_height: 11
  protocol_fund_address: "12svfkP6w5UDJDSCwqH978PvqiqBxKmUnA9em9yAYWYJVRv7wuXY1qhhYpPAm4BDz2mLbFrRmdK3yRhnTqJCZXKHUmoi7NV83HCH2YFpctHNaDdkSiQshsjw2UFUuwdEvcidgaKmF3VJpY5f8RdN"
  admin_address: "12svfkP6w5UDJDSCwqH978PvqiqBxKmUnA9em9yAYWYJVRv7wuXY1qhhYpPAm4BDz2mLbFrRmdK3yRhnTqJCZXKHUmoi7NV83HCH2YFpctHNaDdkSiQshsjw2UFUuwdEvcidgaKmF3VJpY5f8RdN"
  params:
    default_fee_rate_bps: 30
    prv_discount_percent: 25
    trading_protocol_fee_percent: 0
    trading_staking_pool_reward_percent: 10
    staking_pool_share: 
      - "0000000000000000000000000000000000000000000000000000000000000004": 10
      - "0000000000000000000000000000000000000000000000000000000000000006": 20
    mint_nft_require_amount: 1000000000
    max_orders_per_nft: 10
    auto_withdraw_order_limit_amount: 10
    min_prv_reserve_trading_rate: 1000000000000
is_enable_bpv3_stats: false
auto_enable_feature:
  - instantfinality:
      min_trigger: 1
      force_trigger: 1e9
      require_percentage: 90
  - maxcommitteesize48:
      min_trigger: 1e9
      force_trigger: 1e9
      require_percentage: 100
  - unified_token_202205021100:
      min_trigger: 5
      force_trigger: 1000000000
      require_percentage: 90
  # - unified_token_202205051530:
  #     min_trigger: 15
  #     force_trigger: 1000000000
  #     require_percentage: 90
  - blocktime20:
      min_trigger: 2000
      force_trigger: 1000000000
      require_percentage: 90 
  - blocktime10:
      min_trigger: 10892003
      force_trigger: 1000000000
      require_percentage: 90
blocktime_param:
  - "blocktimedef": 40
  - "blocktime20": 20
  - "blocktime10": 10
feature_version:
  - blocktime20: 9

transactions_param:
  lowerbound: 15
  upperbound: 100 
bridge_agg_param:
  admin_address: "12svfkP6w5UDJDSCwqH978PvqiqBxKmUnA9em9yAYWYJVRv7wuXY1qhhYpPAm4BDz2mLbFrRmdK3yRhnTqJCZXKHUmoi7NV83HCH2YFpctHNaDdkSiQshsjw2UFUuwdEvcidgaKmF3VJpY5f8RdN"
  base_decimal: 9 # Use only one time DONOT edit this after deployed
  max_len_of_path: 3
  percent_fee_decimal: 1e6
  default_percent_fee_with_decimal: 100 # 0.01% * 1e6
bc_height_break_point_coin_origin: 1
