name: "local"
net: 0x02
genesis_param:
  initial_incognito:
    - Version: 1
      Type: "s"
      LockTime: 1570159128
      SigPubKey: "5xVSzcZpA3uHmBO5ejENk13iayexILopySACdieLugA="
      Fee: 0
      Sig: "oMJPBLxKgTnfQhMgfvvH68ed0UTuTfl3ofOoWgk8dgvfhovgvued9HH4dXz60rY32H4Y4c85Zd8bSXSnvNhZAA=="
      Proof: "AAAAAAAAAbAAriDnFVLNxmkDe4eYE7l6MQ2TXeJrJ7EguinJIAJ2J4u6ACARCc1/qyLEePe1zSthzmRSqf2VNOlo036JwtDgbNg24yAb6hGuk1tRBVMO4ruHaNEasY09ZiBc4iuK/dpDSyNTCCABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDMoX8yNBbY68SO44umD1CMfz/r0T4YiXhDgDgT6+k4BgdY0V4XYoAAAAAAAAAAAAA="
      PubKeyLastByteSender: 0
  fee_per_tx_kb: 0
  consensus_algorithm: "bls"
  block_timestamp: "2019-11-29T00:00:00.000Z"
  tx_stake: "d0e731f55fa6c49f602807a6686a7ac769de4e04882bb5eaf8f4fe209f46535d"

committee_size:
  max_shard_committee_size: 12
  min_shard_committee_size: 4
  min_beacon_committee_size: 4
  max_beacon_committee_size: 7
  init_shard_committee_size: 4
  init_beacon_committee_size: 4
  shard_committee_size_key_list_v2: 4
  beacon_committee_size_key_list_v2: 4
  number_of_fixed_shard_block_validators: 4
block_time:
  min_beacon_block_interval: 8s
  max_beacon_block_creation: 5s
  min_shard_block_interval: 8s
  max_shard_block_creation: 5s
staking_amount_shard: 1750000000000
active_shards: 2
basic_reward: 400000000
epoch_param:
  number_of_block_in_epoch: 50
  number_of_block_in_epoch_v2: 1000000000000
  epoch_v2_break_point: 1000000000000
  random_time: 25
  random_time_v2: 1000000000000
eth_contract_address: "0xE7b8DA0EC40719b9048CB81Ab5ABb468Da9cC9E0"
bsc_contract_address: "0x6CbCDEBe5449D43c2AaD03da6f2BEE8813a33E6a"
prv_erc20_contract_address: "0xf4933b0288644778f6f2264EaB009fD04fF669a1"
prv_bep20_contract_address: "0x5A15626f6beA715870D46f43f50bE9821368963f"
pdex_erc20_contract_address: "0x9c59b98fcC33f2859A2aB11BC2aAfDcf513b6c33"
pdex_bep20_contract_address: "0xa43F2911dF4a560A1F687Eba359D047753Cd9BD9"
dao_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci" # community fund
centralized_website_payment_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci"
swap_committee_param:
  offset: 1
  swap_offset: 1
  assign_offset: 2
consensus_param:
  consensus_v2_epoch: 1
  staking_flow_v2_height: 1
  enable_slashing_height: 1
  assign_rule_v3_height: 1000000000000
  enable_slashing_height_v2: 1000000000000
  staking_flow_v3_height: 1000000000000
  block_producing_v3_height: 1000000000000
  timeslot: 10
  epoch_break_point_swap_new_key: # read from file key list v2
    - 7000000
beacon_height_break_point_burn_addr: 2
eth_remove_bridge_sig_epoch: 0
replace_staking_tx_height: 1
bc_height_break_point_new_zkp: 2
bc_height_break_point_privacy_v2: 1
coin_v2_lowest_height: 1
enable_feature_flags:
  - PortalRelaying: 1
  - PortalV3: 0
  - PortalV4: 1
portal_v3_height: 1000000000000
tx_pool_version: 0
bsc_param:
  host: "https://data-seed-prebsc-1-s1.binance.org:8545"
pdex_param:
  pdex_v3_break_point_height: 11
  protocol_fund_address: "12svfkP6w5UDJDSCwqH978PvqiqBxKmUnA9em9yAYWYJVRv7wuXY1qhhYpPAm4BDz2mLbFrRmdK3yRhnTqJCZXKHUmoi7NV83HCH2YFpctHNaDdkSiQshsjw2UFUuwdEvcidgaKmF3VJpY5f8RdN"
  admin_address: "12svfkP6w5UDJDSCwqH978PvqiqBxKmUnA9em9yAYWYJVRv7wuXY1qhhYpPAm4BDz2mLbFrRmdK3yRhnTqJCZXKHUmoi7NV83HCH2YFpctHNaDdkSiQshsjw2UFUuwdEvcidgaKmF3VJpY5f8RdN"
  params:
    default_fee_rate_bps: 30
    prv_discount_percent: 25
    trading_protocol_fee_percent: 0
    trading_staking_pool_reward_percent: 10
    staking_pool_share: 
      - "0000000000000000000000000000000000000000000000000000000000000004": 10
      - "0000000000000000000000000000000000000000000000000000000000000006": 20
    mint_nft_require_amount: 1000000000
    max_orders_per_nft: 10
    auto_withdraw_order_limit_amount: 10
    min_prv_reserve_trading_rate: 1000000000000
is_enable_bpv3_stats: false
