version: '2.1'
services:
  constant-dev:
    image: golang:1.11rc1-alpine
    container_name: constant-prototype-dev
    volumes:
      - "../:/go/src/github.com/ninjadotorg/constant"
    command: > 
      sh -c "apk update && apk add --no-cache curl git 
      && curl -Lk https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz -o glide.tar.gz 
      && mkdir ~/glide
      && tar -xzf glide.tar.gz -C ~/glide
      && mv ~/glide/linux-amd64/glide /bin/glide 
      && tail -f /dev/null"
    working_dir: /go/src/github.com/ninjadotorg/constant
    ports:
      - 9333:9333
    networks:
      - constant-net
networks:
  constant-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        -
          subnet: 175.25.0.0/24
        -
          subnet: 2008:3984:3989::/64
